### ISSUE TITLE
Need Dark Mode

### ISSUE THREAD

**Issue by Anikesh02** [Anikesh02/Eldcare#11]
It would be great if someone added dark mode to the website with decent dark colour pallets

**Comment by Koppeks** [comment]
I would like to work on this!

**Comment by Anikesh02** [comment]
> I would like to work on this!

Yeah sure. Make sure to send a PR with a preview (gif, video) attached on what changes you have made.

**Comment by Koppeks** [comment]
As requested this is a video of a short rundown about the changes and the new color palette of dark mode
This works with 2 new sets of colors inside the tailwind config file and a plugin that will check and add the dark variant.

https://github.com/user-attachments/assets/e9ab7549-519a-4ce3-b9d1-10bb55843154

**Comment by Anikesh02** [comment]
@Koppeks If you have some better ideas in your mind to improve Eldcare by adding some features and taking Eldcare to the next level then please raise an issue for adding the feature.

Thank you for your contribution !!
