### ISSUE TITLE
Google Auth

### ISSUE THREAD

**Issue by Anikesh02** [Anikesh02/Eldcare#12]
Currently, the website is taking email and password. It would be great if someone added Google authentication using OAuth or clerk

**Comment by ahammadabdullah** [comment]
@Anikesh02 i can see you used firebase for authentication. You can easily implement google login through firebase or is there any reason you're looking for Oauth or clerk ?

**Comment by Anikesh02** [comment]
> @Anikesh02 i can see you used firebase for authentication. You can easily implement google login through firebase or is there any reason you're looking for Oauth or clerk ?

It would be great if someone added a Google login to the website using anything like (Firebase, OAuth or Clerk). Make sure to send a PR with a preview attached to it.

**Comment by ahammadabdullah** [comment]
> > @Anikesh02 i can see you used firebase for authentication. You can easily implement google login through firebase or is there any reason you're looking for Oauth or clerk ?
> 
> It would be great if someone added a Google login to the website using anything like (Firebase, OAuth or Clerk). Make sure to send a PR with a preview attached to it.

alright let me start working on it by assigning me

**Comment by ahammadabdullah** [comment]
@Anikesh02 when a user registering for the first-time he's providing the info that he's a doctor or a relative and about his gender. But google authentication directly login a user. So do  you have anything in mind how can we solve the issue?

**Comment by Anikesh02** [comment]
> @Anikesh02 when a user registering for the first-time he's providing the info that he's a doctor or a relative and about his gender. But google authentication directly login a user. So do you have anything in mind how can we solve the issue?

To solve this issue we can create a post-login form or modal that users must fill out upon their first login via Google authentication. This form can capture additional details such as whether they are a doctor or a relative and their gender.

**Comment by ahammadabdullah** [comment]
Okay Lets go with the modal. here's the authentication system preview I have implemented 

https://www.loom.com/share/d5a1a2cc1ae84327829a5aebba930de3?sid=be0af3a0-6860-4709-bee9-524285b32d0a

**Comment by ahammadabdullah** [comment]
@Anikesh02  could you please add google provider in your firebase console. 
Authenticaion -> sign-in method -> add new provider -> google

**Comment by Anikesh02** [comment]
> @Anikesh02 could you please add google provider in your firebase console. Authenticaion -> sign-in method -> add new provider -> google

Done

**Comment by ahammadabdullah** [comment]
@Anikesh02 check this out. if its okay I'm opening PR

https://www.loom.com/share/6a5ade1422ea4f7398bc41c3e7712ad9?sid=47b9495e-8d66-4052-a19d-7525c44f5a83

**Comment by Anikesh02** [comment]
> @Anikesh02 check this out. if its okay I'm opening PR
> 
> https://www.loom.com/share/6a5ade1422ea4f7398bc41c3e7712ad9?sid=47b9495e-8d66-4052-a19d-7525c44f5a83

It's good. You can raise the PR

**Comment by Anikesh02** [comment]
@ahammadabdullah If you have some better ideas in your mind to improve Eldcare by adding some features and taking Eldcare to the next level then please raise an issue for adding the feature. 

Thank you for your contribution !!

**Comment by ahammadabdullah** [comment]
Alright. I'll look into it. Thanks.
