### ISSUE TITLE
[BUG] Navbar jumps when scrolling bottom

### ISSUE THREAD

**Issue by ahammadabdullah** [Anikesh02/Eldcare#17]
Navbar is jumping when scrolling down. 
The solution is simple. Make the Navbar sticky with the classnames only without any useEffect. 

https://www.loom.com/share/1add55e27e9743948f3f7b8bc88edfe8?sid=de53418d-da26-46bb-9d45-2fb1c7f61c36

**Comment by ahammadabdullah** [comment]
@Anikesh02  please add the labels and assign me.

**Comment by Anikesh02** [comment]
That's okay @ahammadabdullah. It's not a major bug. Let me know if you want to add more features to EldCare or create a profile page for the user.
Thank you !!

**Comment by ahammadabdullah** [comment]
@Anikesh02 hey its not an issue. i already fixed the bug. What ever If you need it lmk I can open pr anytime. Thanks.

**Comment by Anikesh02** [comment]
> @Anikesh02 hey its not an issue. i already fixed the bug. What ever If you need it lmk I can open pr anytime. Thanks.

Kindly raise an issue for the Profile Page where users can update their profile information and I'll assign it to you.

Thank you !!
