### ISSUE TITLE
[BUG] make the appointment UI more perfect /  good looking 

### ISSUE THREAD

**Issue by Shariar-Hasan** [Anikesh02/Eldcare#18]
apoiintment ui is  not properly showing its placeholder text in dark mode.
and the ui is broken, i want to fix it
![image](https://github.com/user-attachments/assets/b372fc80-d167-4b03-9007-662ece3eca95)

**Comment by Anikesh02** [comment]
@Shariar-Hasan Go ahead. Kindly send a preview (Video,/GIF/Image) of your work while raising a PR.
Thank you !!

**Comment by Shariar-Hasan** [comment]
Ok, got it.
