### ISSUE TITLE
Add Search Feature for Nearby Hospitals Based on Elder's Location

### ISSUE THREAD

**Issue by Khuzaima-Ansari** [Anikesh02/Eldcare#27]
Currently, the application lacks a search feature that allows users to find nearby hospitals based on the elder's location. This limitation reduces the app's utility for users who may need to quickly locate healthcare facilities.

Expected Functionality
The application should enable users to search for nearby hospitals by using the elder's current location. This can be achieved through the integration of location services and possibly connecting to hospital databases.

**Comment by Anikesh02** [comment]
@Khuzaima-Ansari assigned
