### ISSUE TITLE
[BUG] the Apply for Care page UI in dark mode, is not properly styled 

### ISSUE THREAD

**Issue by akashchoudhary436** [Anikesh02/Eldcare#32]
Page in the Light mode the text are visible proper
![image](https://github.com/user-attachments/assets/efdaca8c-1071-45a4-a5ee-1104522b89df)

Page in the Dark mode the text are not visible proper
![image](https://github.com/user-attachments/assets/b43fb7f6-18f9-4232-bc31-004bcfd8bf67)

**Comment by Anikesh02** [comment]
@akashchoudhary436 assigned
